from sdl2 import SDLK_LEFT, SDLK_RIGHT, SDLK_SPACE, SDLK_q

DEMO_MODE = True

# 데모에서 허용할 SDL key 코드들
ALLOWED_KEYS = {SDLK_LEFT, SDLK_RIGHT, SDLK_SPACE, SDLK_q}

# 추가 옵션(원하면 확장)
# DEMO_DISABLE_SAVE = True
# DEMO_SHOW_WATERMARK = True